language: ruby
cache: bundler

services:
  - xvfb

before_install:
  - gem install bundler -v '< 2'

jobs:
  include:
  - rvm: 2.2
    gemfile: gemfiles/Gemfile_Rails_5_2
  - rvm: 2.3
    gemfile: gemfiles/Gemfile_Rails_5_2
  - rvm: 2.4
    gemfile: gemfiles/Gemfile_Rails_5_2
  - rvm: 2.5
    gemfile: gemfiles/Gemfile_Rails_5_2
  - rvm: 2.6
    gemfile: gemfiles/Gemfile_Rails_5_2

